# Generated by Django 4.2.7 on 2023-11-06 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('STP', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
