# Generated by Django 4.2.7 on 2023-11-06 16:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STP', '0004_calendar_task_calendar_stats'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={},
        ),
        migrations.AddField(
            model_name='task',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2023, 11, 7, 16, 38, 22, 355184, tzinfo=datetime.timezone.utc)),
        ),
    ]
