# Generated by Django 4.2.7 on 2023-11-07 00:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STP', '0007_alter_calendar_id_alter_stats_id_alter_task_due_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('choice1', 'Baja'), ('choice2', 'Media'), ('choice3', 'Alta'), ('choice3', 'Sin prioridad')], default='choice4', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2023, 11, 8, 0, 41, 17, 193702, tzinfo=datetime.timezone.utc)),
        ),
    ]
