# Generated by Django 4.2.7 on 2023-11-07 00:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STP', '0008_task_priority_alter_task_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2023, 11, 8, 0, 43, 4, 200657, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('choice1', 'Baja'), ('choice2', 'Media'), ('choice3', 'Alta'), ('choice4', 'Sin prioridad')], max_length=10),
        ),
    ]
