# Generated by Django 4.2.7 on 2023-11-07 01:38

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('STP', '0009_alter_task_due_date_alter_task_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task_calendar',
            name='calendar',
        ),
        migrations.RemoveField(
            model_name='task_calendar',
            name='task',
        ),
        migrations.RenameField(
            model_name='calendar',
            old_name='date',
            new_name='end_date',
        ),
        migrations.AddField(
            model_name='calendar',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='calendar',
            name='events',
            field=models.ManyToManyField(blank=True, to='STP.task'),
        ),
        migrations.AddField(
            model_name='calendar',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='calendar',
            name='title',
            field=models.CharField(default='Untitled Calendar', max_length=200),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2023, 11, 8, 1, 38, 34, 349515, tzinfo=datetime.timezone.utc)),
        ),
        migrations.DeleteModel(
            name='Stats',
        ),
        migrations.DeleteModel(
            name='Task_Calendar',
        ),
    ]
