# Generated by Django 4.2.6 on 2023-11-08 23:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STP', '0013_alter_task_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2023, 11, 9, 23, 53, 26, 405977, tzinfo=datetime.timezone.utc)),
        ),
    ]
