# Generated by Django 4.2.6 on 2023-11-09 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STP', '0014_alter_task_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
