# Generated by Django 4.2.6 on 2023-11-13 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('STP', '0015_alter_task_due_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Calendar',
        ),
    ]
