# Generated by Django 4.2.6 on 2023-11-13 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('STP', '0017_calendar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Calendar',
        ),
    ]
